### PR TITLE
Deprecate zope.site.hooks with zope.deprecation.

### PR DESCRIPTION
**Pull request by thet**
A lot of Plone packages still import from zope.site.hooks, without notice. Let's stop that.

### CODE REVIEW

**Comment by jensens** [comment]
+1 - using clean deprecation is imo much better than just importing a bunch of bbb stuff unnoticed.

**Comment by thet** [comment]
@tseaver is this PR ok for you?

**Comment by tseaver** [comment]
Thanks!

**Comment by thet** [comment]
Thanks for the merge! We should consider removing the hooks module for zope.site 4.1.

**Comment by icemac** [comment]
@thet version 5.0 please as this removal is a backwards incompatible API change.

**Comment by jensens** [comment]
+1 for semantic versioning!

**Comment by thet** [comment]
Updated for 5.0. And added more deprecations: https://github.com/zopefoundation/zope.site/pull/3

**Pull request merged**
